import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY || 're_mock_123');

export async function POST(req) {
  try {
    const { email, report } = await req.json();

    if (!process.env.RESEND_API_KEY) {
      return Response.json({ success: true, message: 'Mock email sent (No API key found)' });
    }

    const { data, error } = await resend.emails.send({
      from: 'AnInterview Reports <onboarding@resend.dev>',
      to: [email],
      subject: `Performance Report: ${report.domain} Interview`,
      html: `
        <div style="font-family: 'Inter', sans-serif; max-width: 600px; margin: 0 auto; padding: 40px; border: 1px solid #f1f5f9; border-radius: 24px; color: #1e293b; background: #ffffff;">
          <div style="text-align: center; margin-bottom: 30px;">
            <h1 style="color: #4facfe; margin: 0; font-size: 28px;">AnInterview</h1>
            <p style="color: #64748b; font-size: 14px; margin-top: 5px;">Your Professional Growth Partner</p>
          </div>

          <h2 style="font-size: 20px; font-weight: 700; margin-bottom: 20px; border-bottom: 2px solid #f1f5f9; padding-bottom: 10px;">
            Mock Interview Analysis: ${report.domain}
          </h2>

          <p>Hello <strong>${report.name || 'Candidate'}</strong>,</p>
          <p>Thank you for completing your ${report.difficulty} level session. Here is a summary of your performance based on our behavioral and technical analytics.</p>
          
          <div style="background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); padding: 30px; border-radius: 16px; margin: 30px 0; text-align: center; color: #ffffff;">
            <p style="font-size: 14px; text-transform: uppercase; letter-spacing: 1px; margin: 0; opacity: 0.9;">Overall Competency Score</p>
            <p style="font-size: 48px; font-weight: 900; margin: 10px 0;">${report.score}/10</p>
          </div>

          <h3 style="font-size: 16px; font-weight: 700; color: #4facfe;">Expert Feedback</h3>
          <p style="line-height: 1.6; background: #f8fafc; padding: 15px; border-radius: 12px;">${report.feedback}</p>

          ${report.roadmap ? `
          <h3 style="font-size: 16px; font-weight: 700; color: #4facfe; margin-top: 25px;">Strategic Improvement Roadmap</h3>
          <ul style="padding-left: 20px; line-height: 1.8;">
            ${report.roadmap.map(item => `<li>${item}</li>`).join('')}
          </ul>` : ''}

          <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #f1f5f9; text-align: center; font-size: 12px; color: #94a3b8;">
            <p>Generated by AnInterview — Elevating Professional Presence.</p>
          </div>
        </div>
      `,
    });

    if (error) {
      return Response.json({ error }, { status: 400 });
    }

    return Response.json({ success: true, data });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
}
